/// Flutter icons SearchIcon
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  SearchIcon
///      fonts:
///       - asset: fonts/SearchIcon.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class SearchIcon {
  SearchIcon._();

  static const _kFontFam = 'SearchIcon';
  static const _kFontPkg = null;

  static const IconData search = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
